force-app/main/default/objects/ProductFixForTelecare__c/ProductFixForTelecare__c.object-meta.xml
<CustomObject>
    <label>ProductFixForTelecare</label>
    <nameField>
        <label>ProductFixForTelecare Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductFixForTelecare</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductFixForTelecare__c/fields/LineDiscountAmount__c.field-meta.xml
<CustomField>
    <fullName>LineDiscountAmount__c</fullName>
    <label>LineDiscountAmount</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/LineGSTAmount__c.field-meta.xml
<CustomField>
    <fullName>LineGSTAmount__c</fullName>
    <label>LineGSTAmount</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/LineTotalAmount__c.field-meta.xml
<CustomField>
    <fullName>LineTotalAmount__c</fullName>
    <label>LineTotalAmount</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/ListPrice__c.field-meta.xml
<CustomField>
    <fullName>ListPrice__c</fullName>
    <label>ListPrice</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/New_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Product_Name__c</fullName>
    <label>New Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/ToProduct__c.field-meta.xml
<CustomField>
    <fullName>ToProduct__c</fullName>
    <label>ToProduct</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductFixForTelecare__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductCleanupServiceForTelecareTest.cls
/**
 * Created by aparnagopalakrishnan on 12/09/23.
 */

@isTest
public class ProductCleanupServiceForTelecareTest {
    @IsTest(SeeAllData = true)
    static void unitTest() {
        Order o = [select OrderId__c from Order where Type = 'recurring' LIMIT 1];
        insert new ProductFixForTelecare__c (Name = o.OrderId__c,
                ToProduct__c = 'TEL-ALM-BUN-MWF5-10',
                Frequency__c ='Fortnightly',
                LineDiscountAmount__c = null,
                LineGSTAmount__c = 115.66,
                LineTotalAmount__c = 1120,
                ListPrice__c = 1104.3478,
                New_Product_Name__c = 'Medical Alarm & Mobile Alarm - Wellington Free Area - Fortnightly',
                TotalPrice__c = 1104.34,
                UnitPrice__c= 1104.34);
        ProductCleanupServiceForTelecareBatch.startBatchProcessing(1);
    }

}